// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc_RJ0uC4nQiMXcbjj9eKcgjBGrTOydko',
    appId: '1:976115202744:web:409aea433fa03f9ad0d24d',
    messagingSenderId: '976115202744',
    projectId: 'push-notifications-saumya',
    authDomain: 'push-notifications-saumya.firebaseapp.com',
    storageBucket: 'push-notifications-saumya.appspot.com',
    measurementId: 'G-NJ68M98DES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOWp4tokTuRzGjtoyBlxtRU1CqXHz9Ric',
    appId: '1:976115202744:android:a9723e25618564ccd0d24d',
    messagingSenderId: '976115202744',
    projectId: 'push-notifications-saumya',
    storageBucket: 'push-notifications-saumya.appspot.com',
  );
}
